// Generated by commsdsl2comms v3.6.5

/// @file
/// @brief Contains definition of <b>"MsgId"</b> field.

#pragma once

#include <cstdint>
#include <type_traits>
#include <utility>
#include "comms/field/EnumValue.h"
#include "comms/options.h"
#include "demo/MsgId.h"
#include "demo/field/FieldBase.h"
#include "demo/field/MsgIdCommon.h"
#include "demo/options/DefaultOptions.h"

namespace demo
{

namespace field
{

/// @brief Definition of <b>"MsgId"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = demo::options::DefaultOptions, typename... TExtraOpts>
class MsgId : public
    comms::field::EnumValue<
        demo::field::FieldBase<>,
        demo::MsgId,
        TExtraOpts...,
        comms::option::def::ValidNumValueRange<0, 11>
    >
{
    using Base = 
        comms::field::EnumValue<
            demo::field::FieldBase<>,
            demo::MsgId,
            TExtraOpts...,
            comms::option::def::ValidNumValueRange<0, 11>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Single value name info entry.
    using ValueNameInfo = demo::field::MsgIdCommon::ValueNameInfo;
    
    /// @brief Type returned from @ref valueNamesMap() member function.
    using ValueNamesMapInfo = demo::field::MsgIdCommon::ValueNamesMapInfo;
    
    /// @brief Name of the field.
    static const char* name()
    {
        return demo::field::MsgIdCommon::name();
    }
    
    /// @brief Retrieve name of the enum value
    static const char* valueName(ValueType val)
    {
        return demo::field::MsgIdCommon::valueName(val);
    }
    
    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::value());
    }
    
    /// @brief Retrieve map of enum value names.
    static ValueNamesMapInfo valueNamesMap()
    {
        return demo::field::MsgIdCommon::valueNamesMap();
    }
    
};

} // namespace field

} // namespace demo


